[build]
  publish = "dist"
  command = "npm run build"

[context.production]
  command = "npm run build"

[context.test]
  command = "npm run deploy:test"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173